version: '3.8'

services:
  dev:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile.dev
    volumes:
      - ..:/workspace:cached
      # Use anonymous volumes to prevent permission issues
      - /workspace/node_modules
      - /workspace/backend/.venv
    environment:
      - NODE_ENV=development
      - PYTHONPATH=/workspace/backend
      - OLLAMA_BASE_URL=http://192.168.0.110:11434
      - CORS_ALLOW_ORIGIN=http://localhost:5173
      - ENV=dev
    ports:
      - '5173:5173' # Frontend dev server
      - '8080:8080' # Backend server
    user: 'node'
    command: sleep infinity
# No need for named volumes now that we're using anonymous volumes
